### ISSUE TITLE
Unable to register for an account using Twitter 

### ISSUE THREAD

**Issue by saramccombs** [messerli90/jobhuntbuddy#6]
Attempted to register for an account using my Twitter account and received the following error:

>This domain (jobhuntbuddy.co) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab.

NOTE: Screenshot not added as a full error message copied above. I can add one should this be more beneficial that I expected. 

## Steps to recreate this error:
1. Click "Get Started for Free" on the main page to register an account.
2. Click "Sign In with Twitter".
3. Receive error below the Twitter and Google Buttons

## Expected Outcome:
I was able to create an account using my Twitter account. 

## Actual Outcome:
I received the above-copied error message and the account was not created, to the best of my knowledge. 

## Steps to Correct Error:
Unknown. But I found [this](https://stackoverflow.com/questions/37344066/firebase-this-domain-is-not-authorized/48475438#48475438) in googling the error message and coming across another github repo with a similar issue raised.

**Comment by messerli90** [comment]
Thank you for posting the issue. 
I've resolved it by adding `jobhuntbuddy.co` as an authorized domain in Firebase. Should be working now.
One caveat with firebase auth is if you create an account with email/password or Google, you then can't sign in with a Twitter account that has the same email.
